# -*- coding: utf-8 -*-
"""Pre_Trained_Glove.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1diQT2xAXRL5cDMg7TREz86ObVbP_9LgZ
"""

## Install glove-python module
!pip install -q glove-python

from google.colab import drive
drive.mount('/content/drive')

from glove import Corpus, Glove

import pandas as pd
import numpy as np

def Load_PreTrained_Glove(GloveFile):
  Glove_Dictionary = {}
  with open(GloveFile,'r') as file:
    for line in file:
      tokens = line.split()
      word = tokens[0]
      word_embedding = np.array([float(val) for val in tokens[1:]])
      Glove_Dictionary[word] = word_embedding
  return Glove_Dictionary

def Calculate_Glove_Embedding(Glove_Dictionary, text):
  
  words = text.split()
  text_embeddings = []
  
  for word in words:
    ## Ignore if word that is not present in vocabulary appears in the text
    if word in Glove_Dictionary:
      word_embedding = Glove_Dictionary[word]
      text_embeddings.append(word_embedding)
  
  text_embeddings = np.array(text_embeddings)
  text_avg_embedding = np.mean(text_embeddings, axis=0)
  
  return text_avg_embedding

def Get_Glove_Embedding(GloveModel_filepath, Input_Data_filepath, colname, Output_Data_filepath=""):
  
  Glove_Dictionary = Load_PreTrained_Glove(GloveModel_filepath)
    
  data = pd.read_csv(Input_Data_filepath)
  
  Data_Embeddings = []
  for row in range(data.shape[0]):
#     print(row)
    text = data.iloc[row][colname]
    text_avg_embedding = Calculate_Glove_Embedding(Glove_Dictionary, text)
    Data_Embeddings.append(text_avg_embedding)

  # print("Data Shape: ", data.shape)
  # print("Data Columns: ", data.columns)
  # print("Data Head: ", data.head )
  
  Data_Text = data[[colname]]
  Data_Labels = data[["0"]]
  Data_Embeddings = pd.DataFrame(Data_Embeddings)
  
  Text_Embedding_Map = pd.concat([Data_Text,Data_Embeddings,Data_Labels], axis=1)
  
  if Output_Data_filepath:
    Text_Embedding_Map.to_csv(Output_Data_filepath)
  
  return Text_Embedding_Map

Text_Embedding_Map = Get_Glove_Embedding("/content/drive/My Drive/glove.twitter.27B/glove.twitter.27B.200d.txt", "/content/Final_Labeled_Data.csv", "Caption_Tokens", "/content/Data_preTrainedGlove_Embeddings.csv")
print(Text_Embedding_Map)