# -*- coding: utf-8 -*-
"""K_Means.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZOcDJhKu-6TG-qTPhkgTqNpxlumLWB59
"""

import pandas as pd
import numpy as np

from sklearn.cluster import KMeans
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
import seaborn as sns

import pickle

## Centroid_init = ["k-means++", "random"]

def K_Means(Data_Filepath, feature_list=[], No_Clusters=2, Centroid_init="k-means++"):
  
  Caption_Data = pd.read_csv(Data_Filepath)
  Data = Caption_Data[feature_list]
  
  kmeans = KMeans(n_clusters=No_Clusters, init=Centroid_init)
  kmeans.fit(Data)
  
  Labels = kmeans.labels_
  labels_df = pd.DataFrame(np.transpose(Labels), columns=["Label"])
  
  labeled_data = pd.concat([Caption_Data, labels_df], axis=1)
  Unique_labels = labeled_data["Label"].unique()
    
  for label in Unique_labels:
    class_data = labeled_data[labeled_data["Label"]==label][["Caption_Tokens","Label"]]
    
    filepath = "/content/class_" + str(label) + "_data.csv"
    class_data.to_csv(filepath)  
    
  return Labels

Data_Filepath = "/content/Positive_Glove_Embeddings.csv"

Embedding_VectorSize = 300
Feature_List = [str(i) for i in range(Embedding_VectorSize)]

Labels = K_Means(Data_Filepath, feature_list=Feature_List)
print("Labels: ", Labels)

## Class 0

Class_0_df = pd.read_csv("/content/class_0_data.csv")
print("CLASS 0 posts : ", Class_0_df.shape[0])

## Class 1

Class_1_df = pd.read_csv("/content/class_1_data.csv")
print("CLASS 1 posts : ", Class_1_df.shape[0])

